name: auto
description: Auto-A simpler Flutter UI automation test solution.
version: 0.0.1
email: vivaskerror@gmail.com
homepage: https://github.com/auto-flutter/auto
environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.22.0'
dependencies:
  flutter:
    sdk: flutter
  archive: ^2.0.0
  protobuf: ^1.0.0
  fixnum: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null

